use crate::commands::info;
use crate::utils::{config, print as p};
use anyhow::Result;
use clap::Args;
use std::fs;
use std::path::PathBuf;

#[derive(Args, Debug)]
pub struct BugReportArgs {
    /// Write the report to a file instead of printing it
    #[arg(short, long, value_name = "FILE")]
    pub output: Option<PathBuf>,
}

pub async fn handle(args: BugReportArgs) -> Result<()> {
    let report = build_report()?;

    match args.output {
        Some(path) => {
            fs::write(&path, &report)?;
            p::success(&format!("Bug report written to {}", path.display()));
        }
        None => print!("{}", report),
    }

    Ok(())
}

fn build_report() -> Result<String> {
    let version = env!("CARGO_PKG_VERSION");
    let os = std::env::consts::OS;
    let arch = std::env::consts::ARCH;

    let cfg = config::load()?;
    let config_path = config::config_path();
    let network = &cfg.network;

    let stellar_cli = info::detect_stellar_cli()
        .map(|p| p.display().to_string())
        .unwrap_or_else(|| "not found".to_string());

    let mut out = String::new();
    out.push_str("## starforge Bug Report\n\n");
    out.push_str("<!--\n");
    out.push_str("  Generated by `starforge bug-report`. Review before posting —\n");
    out.push_str("  remove anything you consider sensitive.\n");
    out.push_str("-->\n\n");

    out.push_str("### Environment\n\n");
    out.push_str(&format!("| Field          | Value |\n"));
    out.push_str(&format!("|----------------|-------|\n"));
    out.push_str(&format!("| starforge      | {version} |\n"));
    out.push_str(&format!("| OS             | {os} ({arch}) |\n"));
    out.push_str(&format!("| Network        | {network} |\n"));
    out.push_str(&format!("| Config file    | {} |\n", config_path.display()));
    out.push_str(&format!("| Stellar CLI    | {stellar_cli} |\n"));
    out.push_str("\n");

    out.push_str("### Steps to Reproduce\n\n");
    out.push_str("1. \n2. \n3. \n\n");

    out.push_str("### Expected Behaviour\n\n");
    out.push_str("<!-- What did you expect to happen? -->\n\n");

    out.push_str("### Actual Behaviour\n\n");
    out.push_str("<!-- What actually happened? Paste the full error output here. -->\n\n");
    out.push_str("```\n\n```\n\n");

    out.push_str("### Additional Context\n\n");
    out.push_str("<!-- Anything else that might be relevant -->\n");

    Ok(out)
}
